POST http://localhost:3000/newpost
Content-Type: application/json

{
    "title": "dfg",
    "description": "Du vraiment hot vraiment different avec plein de mots cool la description de mon post que je suis en train de creer",
    "created_by": "gab"
}

###
GET http://localhost:3000/allPosts


###
GET http://localhost:3000/allPosts/634ab5913cadea56ea33ea55


###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "username": "Test",
    "email": "marie@gmail.com",
    "password": "salut"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "marie@gmail.com",
    "password": "salut"
}

###
POST http://localhost:3000/follower/addfollower
Content-Type: application/json

{
    "user_id": "634c5c669816831c6314934d",
    "post_id": "63486c18be167567450be3e0"
}


###
GET http://localhost:3000/follower/getall


###
GET http://localhost:3000/follower/postfollowers/63486c18be167567450be3e0

###
GET http://localhost:3000/follower/userfollowed/634c5c669816831c6314934d

###
POST http://localhost:3000/post/newpost
Content-Type: application/json

{
    "title": " TEST DELETE ",
    "description": "TEST DELETE",
    "created_by": "TEST DELETE"
}

###
POST http://localhost:3000/post/delete/634f1f5263dcf06ab205e61a